// import './globals.css'
import Global_Context from '@/Global/Global_Context'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin:'0px', padding:'0px'}} >
        <Global_Context>

        {children}
        </Global_Context>
        </body>
    </html>
  )
}
